### ISSUE TITLE
Allow to use yarn

### ISSUE THREAD

**Issue by n0cloud** [cinderblock/node-userid#5]
I'm using version 1.0.0-beta.6 and I'm trying to upgrade the package, but it seem that you're blocking the use of yarn.

I'm not getting an error when I try to install with `--ignore-engines`. 

Can you explain what's the issue with yarn please?

**Comment by cinderblock** [comment]
Hmmm. My intention was to block the use of `yarn` for development, since we use `npm`'s `package-lock.json`. I didn't want to also have a `yarn.lock` and also wanted to block any chance of `package-lock.json` being out of sync with `package.json`.

Are you trying to develop/modify this package? Or are you trying to use it as a dependency? (Install from git or Npm?)

**Comment by n0cloud** [comment]
No, I'm just trying to install the package with yarn

**Comment by cinderblock** [comment]
I see. I'm thinking about how I want to fix this issue because I want to maintain checks forcing `package-lock.json` to be kept in sync.

**Comment by n0cloud** [comment]
You can add a CI that check for it.

**Comment by cinderblock** [comment]
Yeah, in theory using `npm ci` should do it but there are apparently bugs with Npm that break this intentional error.

If you need a short term fix, you should be able to fork this repo and remove the offending `package.json#engines` line. That will allow you to install from your repo as a normal dependency.

To be clear, I fully intend to fix this but I just want to dot my I's and cross my T's before committing.

Thank you very much for the report.
